apiVersion: batch/v1
kind: Job
metadata:
  name: data-ingestion
spec:
  template:
    metadata:
      labels:
        app: gen3job
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: manifest-global
      - name: creds-volume
        secret:
          secretName: indexd-creds
      - name: data-ingestion-job-secret
        secret:
          secretName: data-ingestion-job-secret
      containers:
        # - name: fence
        #   image: quay.io/cdis/fence:master
        #   imagePullPolicy: Always
        #   env:
        #     - name: PYTHONPATH
        #       value: /var/www/fence
        #   volumeMounts:
        #     - name: "config-volume"
        #       readOnly: true
        #       mountPath: "/var/www/fence/fence-config.yaml"
        #       subPath: fence-config.yaml
        #     - name: "fence-google-app-creds-secret-volume"
        #       readOnly: true
        #       mountPath: "/var/www/fence/fence_google_app_creds_secret.json"
        #       subPath: fence_google_app_creds_secret.json
        #     - name: "fence-google-storage-creds-secret-volume"
        #       readOnly: true
        #       mountPath: "/var/www/fence/fence_google_storage_creds_secret.json"
        #       subPath: fence_google_storage_creds_secret.json
        #     - name: "fence-yaml"
        #       mountPath: "/var/www/fence/user.yaml"
        #       subPath: user.yaml
        #   imagePullPolicy: Always
        - name: data-ingestion-pipeline
          image: quay.io/cdis/datastage-data-ingestion:feat_data-ingestion-pipeline
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: "data-ingestion-job-secret"
              readOnly: true
              mountPath: "/.aws/config"
              subPath: config
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: data-ingestion-job-secret
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: data-ingestion-job-secret
                  key: aws_secret_access_key
          command: ["/bin/bash" ]
          args:
            - "-c"
            - |
              ./run.sh
      restartPolicy: Never